const names = {
  AFKS: 'АФК “Система”',
  AFLT: 'Аэрофлот',
  ALRS: 'Алроса',
  CBOM: 'МКБ',
  CHMF: 'Северсталь',
  DSKY: 'Детский мир',
  ENPG: 'Эн+ Груп',
  FIVE: 'Х5',
  FIXP: 'Fixprice',
  GAZP: 'Газпром',
  GLTR: 'Globaltrans',
  GMKN: 'Норникель',
  HYDR: 'Русгидро',
  IRAO: 'Интер РАО',
  LKOH: 'Лукойл',
  MAGN: 'ММК',
  MGNT: 'Магнит',
  MOEX: 'Мосбиржа',
  MTSS: 'МТС',
  NLMK: 'НЛМК',
  NVTK: 'Новатэк',
  OZON: 'OZON',
  PHOR: 'Фосагро',
  PIKK: 'ПИК',
  PLZL: 'Полюс',
  POLY: 'Polymetal',
  ROSN: 'Роснефть',
  RTKM: 'Ростелеком',
  RUAL: 'Русал',
  SBER: 'Сбербанк',
  SBERP: 'Сбербанк (п)',
  SNGS: 'Сургутнефтегаз',
  SNGSP: 'Сургутнефтегаз (п)',
  TATN: 'Татнефть',
  TATNP: 'Татнефть (п)',
  TCSG: 'TCS Group',
  TRNFP: 'Транснефть (п)',
  VKCO: 'VK',
  VTBR: 'ВТБ',
  YNDX: 'Yandex',
};
const companyNameMapping = (companyName): string => {
  return names[companyName];
}

export default companyNameMapping;